
import { HeroSlide } from '../types';
import { getWooConfig } from './wooService';

const CACHE_KEY = 'hero_slides_sql_cache';
const CACHE_DURATION = 15 * 60 * 1000; // 15 Minutes Cache

// Mapping Interface for Backend SQL Structure
interface SqlSlide {
    id: number;
    title: string;
    subtitle: string;
    description: string;
    bg: string;
    image: string;
    cta_text: string;
    cta_link: string;
    sort_order: number;
}

const DEFAULT_SLIDES: HeroSlide[] = [
    {
      id: 1,
      title: "نابغه کوچک خود را کشف کنید",
      subtitle: "آموزش چرتکه",
      desc: "افزایش تمرکز و خلاقیت فرزندتان",
      bg: "from-blue-600 to-indigo-800",
      image: "https://api.kurdkids.ir/wp-content/uploads/2026/01/Plus618.jpg", 
      cta: "شروع کنید",
      link: "/training"
    },
    {
      id: 2,
      title: "فروشگاه ابزار آموزشی",
      subtitle: "خرید آنلاین",
      desc: "بهترین چرتکه‌ها و کتاب‌های آموزشی",
      bg: "from-purple-600 to-pink-800",
      image: "https://api.kurdkids.ir/wp-content/uploads/2026/01/Plus214.jpg",
      cta: "خرید کنید",
      link: "/store"
    }
];

export const heroService = {
  // 1. Synchronous Cache Access
  getCachedSlides: (): HeroSlide[] | null => {
      const cached = localStorage.getItem(CACHE_KEY);
      if (cached) {
          try {
              const parsedCache = JSON.parse(cached);
              return parsedCache.data;
          } catch (e) {
              return null;
          }
      }
      return null;
  },

  // 2. Async Network Fetch (Fresh)
  getSlides: async (skipCache = false): Promise<HeroSlide[]> => {
    // Check Cache
    if (!skipCache) {
        const cached = localStorage.getItem(CACHE_KEY);
        if (cached) {
            const parsedCache = JSON.parse(cached);
            if (Date.now() - parsedCache.timestamp < CACHE_DURATION) {
                return parsedCache.data;
            }
        }
    }

    // Fetch from API
    try {
      const config = getWooConfig();
      const baseUrl = config.url.replace(/\/$/, '');
      
      const response = await fetch(`${baseUrl}/wp-json/lms/v1/slider?ts=${Date.now()}`);
      
      if (!response.ok) throw new Error('Custom API not found or error');
      
      const sqlData: SqlSlide[] = await response.json();
      
      if (Array.isArray(sqlData) && sqlData.length > 0) {
          // Map SQL columns to App types
          const mappedSlides: HeroSlide[] = sqlData.map(s => ({
              id: s.id,
              title: s.title,
              subtitle: s.subtitle,
              desc: s.description, 
              bg: s.bg,
              image: s.image,
              cta: s.cta_text,
              link: s.cta_link
          }));

          // Update Cache
          localStorage.setItem(CACHE_KEY, JSON.stringify({
              data: mappedSlides,
              timestamp: Date.now()
          }));
          
          return mappedSlides;
      }
    } catch (e) {
      // Fallback to cache if network fails
      const cached = localStorage.getItem(CACHE_KEY);
      if (cached) return JSON.parse(cached).data;
    }

    // Fallback Default
    return DEFAULT_SLIDES;
  },

  // --- Admin: Save Slides ---
  saveSlides: async (slides: HeroSlide[], token: string): Promise<HeroSlide[]> => {
    const config = getWooConfig();
    const baseUrl = config.url.replace(/\/$/, '');
    
    const payload = slides.map(s => ({
        title: s.title,
        subtitle: s.subtitle,
        description: s.desc,
        bg: s.bg,
        image: s.image,
        cta: s.cta,
        link: s.link
    }));

    const response = await fetch(`${baseUrl}/wp-json/lms/v1/slider`, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify(payload)
    });

    if (!response.ok) {
        throw new Error(`Error saving slides: ${response.status}`);
    }

    // Force fresh fetch to ensure IDs are synced if generated by DB (though here ID is usually client-side or handled loosely)
    return await heroService.getSlides(true);
  },

  setupDatabase: async (token: string): Promise<void> => {
    const config = getWooConfig();
    const baseUrl = config.url.replace(/\/$/, '');
    
    const response = await fetch(`${baseUrl}/wp-json/lms/v1/setup`, {
        method: 'POST',
        headers: {
            'Authorization': `Bearer ${token}`
        }
    });

    if (!response.ok) {
        throw new Error('خطا در اجرای اسکریپت ساخت جدول');
    }
  },

  resetDefaults: (): HeroSlide[] => {
    localStorage.removeItem(CACHE_KEY);
    return DEFAULT_SLIDES;
  }
};
